version: '3.8'

services:
  consul:
    image: hashicorp/consul:latest
    container_name: local-consul
    ports:
      - "8500:8500" 
      - "8600:8600/udp" 
    command: "agent -dev -ui -client=0.0.0.0"