"""
Generates ocelot.k8s.json from ocelot.json.

Why generated and not hand-written: the two files differ in exactly one respect -
how a downstream service is located. Keeping 44 routes duplicated by hand means
every new endpoint has to be added twice, and the day someone forgets, the
gateway works locally and 404s in the cluster. One source of truth, one
transformation.

    ocelot.json       Consul  : UseServiceDiscovery + ServiceName
    ocelot.k8s.json   K8s DNS : DownstreamHostAndPorts -> <slug>:8080

Run after editing ocelot.json:

    python scripts/generate-ocelot-k8s.py
"""

import json
import pathlib
import re
import sys

CONFIG_DIR = (
    pathlib.Path(__file__).resolve().parent.parent
    / "SellingBuddy/src/ApiGateways/WebApiGateway/Web.ApiGateway/Configurations"
)
SOURCE = CONFIG_DIR / "ocelot.json"
TARGET = CONFIG_DIR / "ocelot.k8s.json"

# Consul service name -> Kubernetes Service name (the canonical slug).
# These must match the Service objects the Helm chart renders, character for
# character: the gateway resolves them straight through kube-dns.
SLUGS = {
    "IdentityService": "identity",
    "CatalogService": "catalog",
    "BasketService": "basket",
    "OrderService": "order",
    "PaymentService": "payment",
}

CONTAINER_PORT = 8080


def strip_jsonc(text: str) -> str:
    """Drops // and /* */ comments, which ocelot.json uses as section headers."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"^\s*//.*?$", "", text, flags=re.M)
    return text


def main() -> int:
    config = json.loads(strip_jsonc(SOURCE.read_text(encoding="utf-8")))

    unknown = set()
    for route in config.get("Routes", []):
        name = route.pop("ServiceName", None)
        route.pop("UseServiceDiscovery", None)

        if name is None:
            continue

        slug = SLUGS.get(name)
        if slug is None:
            unknown.add(name)
            continue

        route["DownstreamHostAndPorts"] = [{"Host": slug, "Port": CONTAINER_PORT}]

    if unknown:
        print(f"Unmapped ServiceName(s): {sorted(unknown)}", file=sys.stderr)
        print("Add them to SLUGS before deploying.", file=sys.stderr)
        return 1

    # Discovery is Kubernetes' job here; leaving the provider configured would
    # make the gateway try to reach a Consul agent that does not exist.
    config.get("GlobalConfiguration", {}).pop("ServiceDiscoveryProvider", None)

    header = (
        "// GENERATED by scripts/generate-ocelot-k8s.py - do not edit by hand.\n"
        "// Source: ocelot.json. Re-run the script after changing routes.\n"
    )
    TARGET.write_text(header + json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"{TARGET.name}: {len(config.get('Routes', []))} routes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
