version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: local-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SellingBuddyStrongP@ssw0rd!
    ports:
      - "1433:1433"